- name: Update packages
  yum: 
    name: "*"
    state: latest

- name: Download required packages
  yum:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: Install OpenShift files
  yum:
    name: atomic-openshift-utils
    state: present

- name: Start and enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes