- name: Update packages
  yum: 
    name: "*"
    state: latest

- name: Download required packages
  yum:
    state: present
    name: "{{ item }}"
  with_items: "{{ packages }}"

- name: Install OpenShift files
  yum:
    name: atomic-openshift-utils
    state: present

- name: Start and enable NetworkManager
  systemd:
    name: NetworkManager
    state: started
    enabled: yes

#nmcli con mod "System eth0" ipv4.method manual ipv4.dns 10.0.10.10 ipv4.dns-search ocp.lab ipv4.addresses 10.0.10.13/32 ipv4.gateway 10.0.10.1
- name: Configure NetworkManager
  nmcli:
    conn_name: System eth0
    ifname: eth0
    type: ethernet
    ip4: "{{ inventory_hostname }}"
    gw4: "{{ network.gateway }}"
    dns4:
    - "{{ nodes['ans.ocp.lab']['ip'] }}"
    autoconnect: yes
    state: present
  notify:
  - Restart NetworkManager