host_image:
  name: CentOS-7-x86_64-GenericCloud-1801-01.qcow2
  url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1801-01.qcow2
  checksum: fb0f10fe4a2e9eaaf2d55153289dcb5ddd08e21bc080f92f2138588731df29d6
  size: 15G
oc_url: https://github.com/openshift/origin/releases/download/v3.7.1/openshift-origin-client-tools-v3.7.1-ab0f056-linux-64bit.tar.gz
network:
  name: ocp.lab
  forward_interface: wlp4s0
  bridge_name: virbr1
  mac: 52:54:00:aa:dc:1c
  network: 10.0.10.0
  netmask: 255.255.255.0
  broadcast: 10.0.10.255
  gateway: 10.0.10.1
  dhcp_start: 10.0.10.10
  dhcp_end: 10.0.10.20
nodes:
  ans.ocp.lab:
    ip: 10.0.10.10
    mac: 52:54:00:6c:3c:01
    memory: 2048
    cpus: 1
    extra_disk_size: 50G
  mas.ocp.lab:
    ip: 10.0.10.11
    mac: 52:54:00:0c:c2:9c
    memory: 4096
    cpus: 1
    extra_disk_size: 5G
  inf.ocp.lab:
    ip: 10.0.10.12
    mac: 52:54:00:07:ae:0a
    memory: 8196
    cpus: 1
    extra_disk_size: 5G
  app.ocp.lab:
    ip: 10.0.10.13
    mac: 52:54:00:3a:d1:62
    memory: 2048
    cpus: 1
    extra_disk_size: 5G