user: "{{ lookup('env','USER') }}"
packages:
- NetworkManager
- NetworkManager-glib
- wget 
- git 
- net-tools 
- bind-utils 
- iptables-services 
- bridge-utils 
- bash-completion 
- kexec-tools 
- sos 
- psacct
- centos-release-openshift-origin